/*
 * @Author: BINGWU
 * @Date: 2024-06-11 17:16:16
 * @LastEditors: BINGWU HuJiaCheng2003@163.com
 * @LastEditTime: 2024-06-25 23:31:59
 * @FilePath: \twitch-clone\app\layout.tsx
 * @Describe: 
 * @Mark: ૮(˶ᵔ ᵕ ᵔ˶)ა
 */
/*
 * @Author: BINGWU
 * @Date: 2024-06-11 17:16:16
 * @LastEditors: BINGWU HuJiaCheng2003@163.com
 * @LastEditTime: 2024-06-25 23:18:08
 * @FilePath: \twitch-clone\app\layout.tsx
 * @Describe: 
 * @Mark: ૮(˶ᵔ ᵕ ᵔ˶)ა
 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en' className='h-full'>
        <body className='h-full'>
          <div>
            <UserButton> </UserButton>
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
